columns:
  case_id: category
  continent: category
  education_of_employee: category
  has_job_experience: category
  requires_job_training: category
  no_of_employees: int
  yr_of_estab: int
  region_of_employment: category
  prevailing_wage: int
  unit_of_wage: category
  full_time_position: category
  case_status: category
  
target_columns : 
  case_status

numerical_column :
  no_of_employees
  yr_of_estab
  prevailing_wage

categorical_column :
  case_id
  continent
  education_of_employee
  has_job_experience
  requires_job_training
  region_of_employment
  unit_of_wage
  full_time_position
  case_status
